name: arcgis-pangeo
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pangeo-notebook
#  - esri::arcgis=2.0.0
## Utilities
  - pip
  - nodejs # for installing jupyterlab-widgets
  - ipywidgets
##
  - jupyterlab=2.2.9
  - jupyterlab-git
  - jupyter-resource-usage
