name: notebook
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - rioxarray
  - xarray>=2022.12
  - h5netcdf
  - netcdf4
  - gdal~=3.6
  - geopandas
  - rasterio
  - pip
  - bottleneck
  - esri::arcgis=2.0.0
## These are needed for jupyterhub functioning
  - jupyterhub-singleuser
  - ipywidgets
  - jupyterlab=2.2.9
  - jupyterlab-git
  - jupyter-resource-usage
  - jupytext
