name: Docker Image CI coastwatch patch
on:
  workflow_dispatch: null
  push:
    branches: coastwatch-patch
    paths: 
      - 'images/coastwatch/**'
      - '.github/workflows/docker-image-coastwatch_patch.yml'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        if: github.repository == 'nmfs-opensci/container-images'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build the Docker image
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker build images/coastwatch -f images/coastwatch/Dockerfile  --tag ghcr.io/nmfs-opensci/container-images/coastwatch-patch:latest
      - name: Publish
        if: github.repository == 'nmfs-opensci/container-images'
        run: |
          docker push ghcr.io/nmfs-opensci/container-images/coastwatch-patch:latest

